servers:
  vars:
    pgp_public_key: https://apt.releases.teleport.dev/gpg
    teleport_version: stable/v12

  hosts:
    teleport-server.smatflow.smfl:
      ansible_user: teleport

    code-server.smatflow.smfl:
      ansible_user: code

    database-server.smatflow.smfl:
      ansible_user: database

    gitlab-runner-server.smatflow.smfl:
      ansible_user: runner

    gitlab-server.smatflow.smfl:
      ansible_user: gitlab

    ipa-server.smatflow.smfl:
      ansible_user: freeipa

    mail-server.smatflow.smfl:
      ansible_user: ubuntu

    pihole-server.smatflow.smfl:
      ansible_user: pihole

    portainer-server.smatflow.smfl:
      ansible_user: portainer

    proxymanager-server.smatflow.smfl:
      ansible_user: proxymanager

    taiga-server.smatflow.smfl:
      ansible_user: taiga

    wireguard-server.smatflow.smfl:
      ansible_user: wireguard
